name: run-tests

on: [push]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      # Configured following guide at:
      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry" # caching dependencies from poetry.lock

      - name: Install Poetry dependencies (CPU)
        run: poetry install -E cpu

      - name: Run unit tests with coverage
        run: poetry run pytest tests/unit --cov=./ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # - name: Run pytest integration tests
      #   run: poetry run pytest tests/integration
      # - name: Run pytest end-to-end tests
      #   run: poetry run pytest tests/end_to_end
